name: Docker Image Build & Test

# 実行するイベントの指定
on:
  # 指定ブランチで指定ファイルがPUSHされたときに実行する
  push:
    paths:
      - 'docker/**'
      - '.github/workflows/build-release.yml'

# 環境変数の設定
env:
  DOCKER_BUILDKIT: 1
  RESISTRY_URL: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: base-kit
  DOCKER_ROOT_DIR: ./docker
  DOCKER_FILE: ./base/Dockerfile
  TEST_VERSION: test.${{ github.run_number }}
  RELEASE_VERSION: 4.1.1


jobs:
  # ビルドとテストを実施し、テストにPASSすれば、仮バージョンでプッシュ
  build-test:

    runs-on: ubuntu-latest
  
    steps:
      # 環境準備
      - name: Checkout repository
        uses: actions/checkout@v2

      # Dockerイメージのビルド
      - name: Build Docker Image
        run: docker build --file ${{ env.DOCKER_FILE }} --tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_ROOT_DIR }}

      # Dockerイメージのテスト
      - name: Test Docker Image
        id: image-test
        run: |
          echo ${{ secrets.GHCR_PASSWD }}
          docker run -d --rm --name ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }} tail -f /dev/null && docker exec -t ${{ env.IMAGE_NAME }} echo "This is test echo."

      # ghcr.ioにログイン
      - name: Login to ghrc.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWD }}

      # Dockerイメージのプッシュ
      - name: Push Docker Image
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TEST_VERSION }}
          docker push ${{ env.RESISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.TEST_VERSION }}
