name: Docker Base Image Build & Publish

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    paths:
      - 'docker/base/**'
      - 'docker/custom/**'
      - '.github/workflows/docker-publish.yml'

env:
  DOCKER_BUILDKIT: 1
  BASE_IMAGE_NAME: gpack-base
  BASE_DOCKER_FILE: docker/base/Dockerfile
  CUSTOM_IMAGE_NAME: gpack-custom
  CUSTOM_DOCKER_FILE: docker/custom/Dockerfile
  RELEASE_VERSION: 0.0.1
  TEST_VERSION: test.${{ github.run_number}}
  RESISTRY_URL: ghcr.io/${{ github.repository_owner }}/${{ env.BASE_IMAGE_NAME }}

jobs:
  # Build and Push add Test Tag
  build-and-push-for-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.BASE_DOCKER_FILE }}
          push: true
          tags: ${{ env.RESISTRY_URL }}:${{ env.TEST_VERSION }}

  # Run Tests.
  base-test:
    needs: build-and-push-for-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWD }}

      - name: Base Image Tests
        run: |
            # test base image
            docker run --rm ${{ env.RESISTRY_URL }}:${{ env.TEST_VERSION }} \
                echo "TEST ECHO: test base docker image"

  # Push custom image to GitHub Packages.
  #  custom-push:
  #    # Ensure test job passes before pushing image.
  #    needs: base-push
  #
  #    runs-on: ubuntu-latest
  #    if: github.event_name == 'push'
  #
  #    steps:
  #      - uses: actions/checkout@v2
  #
  #      - name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v1
  #
  #      - name: Login to GitHub Container Registry
  #        uses: docker/login-action@v1
  #        with:
  #          registry: ghcr.io
  #          username: ${{ github.repository_owner }}
  #          password: ${{ secrets.CR_PAT }}
  #
  #      - name: Build and push
  #        uses: docker/build-push-action@v2
  #        with:
  #          context: .
  #          file: ${{ env.CUSTOM_DOCKER_FILE }}
  #          push: true
  #          tags: |
  #            ghcr.io/${{ github.repository_owner }}/${{ env.CUSTOM_IMAGE_NAME }}:latest
  #            ghcr.io/${{ github.repository_owner }}/${{ env.CUSTOM_IMAGE_NAME }}:${{ env.RELEASE_VERSION }}

